name: Build & Push

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag
        id: vars
        run: echo "TAG=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Debug tag
        run: |
          echo "Tag is: ${{ steps.vars.outputs.TAG }}"

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: manojthedonut/tsingress-controller:${{ steps.vars.outputs.TAG }}
